# --- Day 9: Mirage Maintenance ---

You ride the camel through the sandstorm and stop where the ghost's maps told you to stop. The sandstorm subsequently subsides, somehow seeing you standing at an oasis!

The camel goes to get some water and you stretch your neck. As you look up, you discover what must be yet another giant floating island, this one made of metal! That must be where the parts to fix the sand machines come from.

There's even a hang glider partially buried in the sand here; once the sun rises and heats up the sand, you might be able to use the glider and the hot air to get all the way up to the metal island!

While you wait for the sun to rise, you admire the oasis hidden here in the middle of Desert Island. It must have a delicate ecosystem; you might as well take some ecological readings while you wait. Maybe you can report any environmental instabilities you find to someone so the oasis can be around for the next sandstorm-worn traveler.



You pull out your handy Oasis And Sand Instability Sensor and analyze your surroundings. The OASIS produces a report of many values and how they are changing over time (your puzzle input). Each line in the report contains the history of a single value. For example:
```
0 3 6 9 12 15
1 3 6 10 15 21
10 13 16 21 30 45
```


To best protect the oasis, your environmental report should include a prediction of the next value in each history. To do this, start by making a new sequence from the difference at each step of your history. If that sequence is not all zeroes, repeat this process, using the sequence you just generated as the input sequence. Once all of the values in your latest sequence are zeroes, you can extrapolate what the next value of the original history should be.

In the above dataset, the first history is 0 3 6 9 12 15. Because the values increase by 3 each step, the first sequence of differences that you generate will be 3 3 3 3 3. Note that this sequence has one fewer value than the input sequence because at each step it considers two numbers from the input. Since these values aren't all zero, repeat the process: the values differ by 0 at each step, so the next sequence is 0 0 0 0. This means you have enough information to extrapolate the history! Visually, these sequences can be arranged like this:
```
0   3   6   9  12  15
  3   3   3   3   3
    0   0   0   0
```


To extrapolate, start by adding a new zero to the end of your list of zeroes; because the zeroes represent differences between the two values above them, this also means there is now a placeholder in every sequence above it:
```
0   3   6   9  12  15   B
  3   3   3   3   3   A
    0   0   0   0   0
```


You can then start filling in placeholders from the bottom up. A needs to be the result of increasing 3 (the value to its left) by 0 (the value below it); this means A must be 3:
```
0   3   6   9  12  15   B
  3   3   3   3   3   3
    0   0   0   0   0
```


Finally, you can fill in B, which needs to be the result of increasing 15 (the value to its left) by 3 (the value below it), or 18:
```
0   3   6   9  12  15  18
  3   3   3   3   3   3
    0   0   0   0   0
```
So, the next value of the first history is 18.



Finding all-zero differences for the second history requires an additional sequence:
```
1   3   6  10  15  21
  2   3   4   5   6
    1   1   1   1
      0   0   0
```


Then, following the same process as before, work out the next value in each sequence from the bottom up:
```
1   3   6  10  15  21  28
  2   3   4   5   6   7
    1   1   1   1   1
      0   0   0   0
```
So, the next value of the second history is 28.



The third history requires even more sequences, but its next value can be found the same way:
```
10  13  16  21  30  45  68
   3   3   5   9  15  23
     0   2   4   6   8
       2   2   2   2
         0   0   0
```
So, the next value of the third history is 68.



If you find the next value for each history in this example and add them together, you get 114.

Analyze your OASIS report and extrapolate the next value for each history. What is the sum of these extrapolated values?

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import re

In [3]:
# Use the below conditional to determine when to stop in our list.
zeroArray = np.array([])
allZeroes = not zeroArray.any()
print(allZeroes)

True


In [4]:
randomArray = np.array([1, 0, 0, 0, 2])
notZeroes = not randomArray.any()
print(notZeroes)

False


In [5]:
# Use the below to find the difference between consecutive numbers in an array.
diffArray = np.array([1, 2, 3, 4, 5, 6])
consecDiff = np.ediff1d(diffArray)
print(consecDiff)

[1 1 1 1 1]


## Recursive Function 
We need the list of numbers to find the difference between the numbers, put that into a sequence.<br>
Once the sequence is just zeros, work in reverse to determine the next number.

We then need to do the same, but to add the number on to the end of the sequence above it. 

From the above functions in NumPy we should be able to implement it.

In [6]:
def gettingToZero(data):
    if not data.any():
        return data
    else:
        return gettingToZero(data)

In [7]:
sampleData = '''0 3 6 9 12 15
1 3 6 10 15 21
10 13 16 21 30 45'''

In [8]:
print(sampleData.splitlines())

['0 3 6 9 12 15', '1 3 6 10 15 21', '10 13 16 21 30 45']


In [19]:
sumOfSequence = []

for lines in sampleData.splitlines():
    digits = re.findall(r'(\d+)(?:\s*)', lines)
    digits = np.array([int(x) for x in digits])
    # print(digits)

    difference = digits
    levelsList = []
    while difference.any() or (difference[-1] != difference [-2]):
        difference = np.ediff1d(difference)
        levelsList.append(difference)
        # print(difference)
    
    difference = 0
    for levels in reversed(levelsList):
        difference = levels[-1] + difference
        # print(difference)

    nextNumberSequence = digits[-1] + difference
    sumOfSequence.append(nextNumberSequence)

print(sum(sumOfSequence))
    

114


In [10]:
# sumOfSequence = []

# # Read the data line by line
# for lines in sampleData.splitlines():
#     digits = re.findall(r'(\d+)(?:\s*)', lines)
#     digits = [int(x) for x in digits]
#     print(digits)

#     # find the difference between each value in the list.
#     difference = digits
#     levelsList = []
#     while difference[-1] != 0 and difference[-2] != 0:
#         difference = [j-i for i, j in zip(difference[:-1], difference[1:])]
#         levelsList.append(difference)
#         print(difference)
    
#     difference = 0
#     for levels in reversed(levelsList):
#         difference = levels[-1] + difference
#         print(levels)

#     # print(digits[-1])
#     nextNumberSequence = digits[-1] + difference
#     sumOfSequence.append(nextNumberSequence)
#     print()
# print(sum(sumOfSequence))


[0, 3, 6, 9, 12, 15]
[3, 3, 3, 3, 3]
[0, 0, 0, 0]
[0, 0, 0, 0]
[3, 3, 3, 3, 3]

[1, 3, 6, 10, 15, 21]
[2, 3, 4, 5, 6]
[1, 1, 1, 1]
[0, 0, 0]
[0, 0, 0]
[1, 1, 1, 1]
[2, 3, 4, 5, 6]

[10, 13, 16, 21, 30, 45]
[3, 3, 5, 9, 15]
[0, 2, 4, 6]
[2, 2, 2]
[0, 0]
[0, 0]
[2, 2, 2]
[0, 2, 4, 6]
[3, 3, 5, 9, 15]

114


In [11]:
# sumOfSequence = []
# for lines in sampleData.splitlines():
#     digits = re.findall(r'(\d+)(?:\s*)', lines)
#     digits = [int(x) for x in digits]
#     y = np.array(digits)
#     x = []
#     for i,v in enumerate(digits):
#         x.append(i)
#     x = np.array(x)
    
#     # calculate polynomial
#     z = np.polyfit(x, y, 3)
#     f = np.poly1d(z)

#     # calculate new x's and y's
#     x_new = np.linspace(x[0], x[-1], 50)
#     y_new = f(x_new)

#     plt.plot(x,y,'o', x_new, y_new)
#     plt.xlim([x[0]-1, x[-1] + 1 ])
#     plt.show()

In [12]:

# for numberOf, lines in enumerate(sampleData.splitlines()):
#     digits = re.findall(r'(\d+)(?:\s*)', lines)
#     digits = [int(x) for x in digits]
#     # print(digits)
#     tempList = []
#     for i, v in enumerate(digits):
#         tempList.append(i)
#     # print(tempList)
    
#     # dydx = np.diff(tempList)/np.diff(digits)
#     # dydx = 1 / dydx
#     # print(dydx)
    
#     # x.append(digits)
#     # y.append(tempList)

# # print(x)
# # print(y)


#     # dydx = np.diff(tempList)/np.diff(digits)
#     # dydx = list(1 / dydx)
        
#     dxdy = list(np.diff(digits)/np.diff(tempList))    
#     while dxdy[1:] != dxdy [:-1]:
#         tempList = []
#         # digits = []
#         for i, v in enumerate(dxdy):
#             # digits.append(v)
#             tempList.append(i)
#         dxdy = list(np.diff(dxdy)/np.diff(tempList))
#         # dydx = np.diff(tempList)/np.diff(dydx)
#         # dydx = list(1 / dydx)
#         print(tempList)
#     print(digits)
#     print(dxdy)
        
#     print()
    

In [32]:
with open(r"Input/2023-12-09.txt") as f:
    data = f.read()
    f.close

In [24]:
sumOfSequence = []

for lines in data.splitlines():
    digits = re.findall(r'(\d+)(?:\s*)', lines)
    digits = np.array([int(x) for x in digits])
    # print(digits)

    difference = digits
    levelsList = []
    try:
        while difference[-1] != difference[-2]:
            difference = np.ediff1d(difference)
            levelsList.append(difference)
            print(difference)
    except IndexError:
        while difference.any():
            difference = np.ediff1d(difference)
            levelsList.append(difference)
            print(difference)
    
    if not levelsList[-1].any() == True:
        del levelsList[-1]

    difference = 0
    for levels in reversed(levelsList):
        difference = levels[-1] + difference
        print(difference)

    nextNumberSequence = digits[-1] + difference
    sumOfSequence.append(nextNumberSequence)

print(sum(sumOfSequence))
    

[      3       7       3      -9      -5      37     244     770    1993
    4727   10740   23710   50873  105693  211990  410124  766135 1385367
 2433421 4169933]
[      4      -4     -12       4      42     207     526    1223    2734
    6013   12970   27163   54820  106297  198134  356011  619232 1048054
 1736512]
[    -8     -8     16     38    165    319    697   1511   3279   6957
  14193  27657  51477  91837 157877 263221 428822 688458]
[     0     24     22    127    154    378    814   1768   3678   7236
  13464  23820  40360  66040 105344 165601 259636]
[   24    -2   105    27   224   436   954  1910  3558  6228 10356 16540
 25680 39304 60257 94035]
[  -26   107   -78   197   212   518   956  1648  2670  4128  6184  9140
 13624 20953 33778]
[  133  -185   275    15   306   438   692  1022  1458  2056  2956  4484
  7329 12825]
[-318  460 -260  291  132  254  330  436  598  900 1528 2845 5496]
[ 778 -720  551 -159  122   76  106  162  302  628 1317 2651]
[-1498  1271  -710   

In [15]:
# sumOfSequence = []
# for lines in data.splitlines():
#     digits = re.findall(r'(\d+)(?:\s*)', lines)
#     digits = [int(x) for x in digits]
#     print(digits)

#     difference = digits
#     levelsList = []
#     # while sum(difference) != 0:
#     while difference[1:] != difference[:-1]:
#         difference = [j-i for i, j in zip(difference[:-1], difference[1:])]
#         levelsList.append(difference)
#         print(difference)
    
#     levelsList = list(filter(None,levelsList))

#     difference = 0
#     for levels in reversed(levelsList):
#         print(difference)
#         difference = levels[-1] + difference
#         print(levels, difference)
#         print()

#     # print(digits[-1])
#     nextNumberSequence = digits[-1] + difference
#     sumOfSequence.append(nextNumberSequence)
#     print(nextNumberSequence)
#     print()
# print(sum(sumOfSequence))
